//example program to handle division/0 exception
#include <iostream>
using namespace std;

int main()
{
    /*
    try
    {
        if(denum==0)
        {
            throw "division by zero!";
        }
        cout<<"the division of"
    }
    catch(char a[])
    {
        cout<<"Exception caught"<<a<<endl;
    }
    */
    
}